# Makefile for lab4 stream-socket server/client program

CC = gcc
OBJCSS = server_client5.c

CFLAGS = -g -Wall -lm

#setup for system
nLIBS = 

all: client5

client4: $(OBJCSS)
	$(CC) $(CFLAGS) -o $@ $(OBJCSS) $(LIBS)

clean:
	rm client5